# Generated by Django 4.0.4 on 2022-05-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='имя')),
                ('last_name', models.CharField(max_length=70, verbose_name='фамилия')),
                ('can_create', models.BooleanField(default=True, verbose_name='может создавать тесты')),
                ('status', models.CharField(max_length=50, verbose_name='статус пользователя: студент/учитель')),
                ('login', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='логин')),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
                'db_table': 'account',
            },
        ),
    ]
