# Generated by Django 4.0.4 on 2022-05-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название факультета')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('npp', models.PositiveSmallIntegerField(default=0, verbose_name='сортировка')),
            ],
            options={
                'verbose_name': 'факультет',
                'verbose_name_plural': 'факультеты',
                'db_table': 'facultet',
                'ordering': ('npp',),
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название предмета')),
                ('kurs', models.IntegerField(verbose_name='номер курса')),
                ('semestr', models.IntegerField(verbose_name='номер семестра')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('npp', models.PositiveSmallIntegerField(default=0, verbose_name='сортировка')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'db_table': 'predmet',
                'ordering': ('npp',),
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название темы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('npp', models.PositiveSmallIntegerField(default=0, verbose_name='сортировка')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_bilet.predmet', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
                'db_table': 'tema',
                'ordering': ('npp',),
            },
        ),
        migrations.CreateModel(
            name='Vopros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(blank=True, verbose_name='описание вопроса')),
                ('level', models.IntegerField(default=1, verbose_name='сложность вопроса')),
                ('ball', models.IntegerField(default=1, verbose_name='количество баллов')),
                ('tema.html', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_bilet.tema.html', verbose_name='тема')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'db_table': 'vopros',
            },
        ),
        migrations.CreateModel(
            name='Specialnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название специальности')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('npp', models.PositiveSmallIntegerField(default=0, verbose_name='сортировка')),
                ('facultet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_bilet.facultet', verbose_name='факультет')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'специальности',
                'db_table': 'specialnost',
                'ordering': ('npp',),
            },
        ),
        migrations.AddField(
            model_name='predmet',
            name='specialnost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_bilet.specialnost', verbose_name='специальность'),
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.CharField(max_length=150, verbose_name='ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='правильный ответ')),
                ('vopros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_bilet.vopros', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'db_table': 'otvet',
            },
        ),
    ]
